update pre-push

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,3 +1,37 @@
 #!/bin/sh
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
+reset_color='\033[0m'
+black='\033[0;30m'
+red='\033[0;31m'
+green='\033[0;32m'
+yellow='\033[0;33m'
+blue='\033[0;34m'
+purple='\033[0;35m'
+cyan='\033[0;36m'
+white='\033[0;37m'
+darkgray='\033[1;30m'
+lightred='\033[1;31m'
+lightgreen='\033[1;32m'
+lightyellow='\033[1;33m'
+lightblue='\033[1;34m'
+lightpurple='\033[1;35m'
+lightcyan='\033[1;36m'
+lightwhite='\033[1;37m'
+
+ECHO="echo"
+# "bash"
+current_shell=$(ps -p $$ | awk 'NR==2')
+if [[ $current_shell == *"bash"* ]]; then
+    ECHO="echo -e"
+fi
+
+
+# git-lfs 관련
+command -v git-lfs >/dev/null 2>&1 || {
+    echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n";
+    $ECHO "${green}[.githooks/pre-push] succeeded~${reset_color}"
+    exit 2;
+}
 git lfs pre-push "$@"
+
+
+$ECHO "${green}[.githooks/pre-push] succeeded~${reset_color}"
